INSERT INTO "FORMATION"."FORMATION" (NOM) VALUES ('LSI')

INSERT INTO "FORMATION"."ETUDIANT" (PRENOM, ID_FORMATION) VALUES ('Majd', '1')
INSERT INTO "FORMATION"."ETUDIANT" (PRENOM, ID_FORMATION) VALUES ('Mahmoud', '1')
INSERT INTO "FORMATION"."ETUDIANT" (PRENOM, ID_FORMATION) VALUES ('Mariam', '1')
INSERT INTO "FORMATION"."ETUDIANT" (PRENOM, ID_FORMATION) VALUES ('Marwa', '1')